### ISSUE TITLE
inv (nxn) not working correctly

### ISSUE THREAD

**Issue by michalkielan** [michal915/MatrixLibs#2]

**Comment by JaroslawWiosna** [comment]
That's because of 
`T det(const Matrix<T, n, n>& A)`
(n >= 4)
_is not implemented._

Please, consider changing status to **blocked**, and creating separate issue about det [n>=4]

Once _det() for n>=4_ is implemented, _inv() for n>=4_ should be working correctly.

**Comment by michalkielan** [comment]
try on 3x3, or hardcode detA

**Comment by michalkielan** [comment]
Nie działa Panie,  :P, dodaj doxygenowe komenty w concagenate

**Comment by JaroslawWiosna** [comment]
check #5

**Comment by JaroslawWiosna** [comment]
What was wrong:
- getminor was implemented ....not good enough :D 
- half of the matrix should be multiplied by -1... and the other half shouldn't. It turned out that those numbers which shouldn't be multiplied was multiplied, etc.

ATTENTION!
In tests I used matrix 4x4 with det=-1 !
That's because det(nxn) n>=4 is hardcoded!
